# Generated by Django 6.0.6 on 2026-06-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('barrio', models.CharField(db_index=True, max_length=100)),
                ('rooms', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('surface_total', models.FloatField(blank=True, null=True)),
                ('surface_covered', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_m2', models.FloatField(blank=True, null=True)),
                ('property_type', models.CharField(default='Departamento', max_length=50)),
                ('amenity_garage', models.BooleanField(default=False)),
                ('amenity_pool', models.BooleanField(default=False)),
                ('amenity_security', models.BooleanField(default=False)),
                ('is_luminous', models.BooleanField(default=False)),
                ('near_transport', models.BooleanField(default=False)),
                ('is_a_estrenar', models.BooleanField(default=False)),
                ('is_reciclado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['barrio'], name='propiedades_barrio_4f5267_idx'), models.Index(fields=['price'], name='propiedades_price_2e7d0d_idx'), models.Index(fields=['rooms'], name='propiedades_rooms_dd2497_idx')],
            },
        ),
    ]
